version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_qda
    restart: always
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: quer-durch-asien
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
